from models.party import PartyProfile


PARTY_PROFILES = {
    "ПКП- Ново Начало": PartyProfile(
        name="ПКП- Ново Начало",
        economic_position=-0.30,
        cultural_position=0.90,
        regime_status=1.00,
        urban_appeal=0.20,
        working_class_appeal=0.95,
        traditionalist_appeal=0.90,
        progressive_appeal=0.05,
        minority_muslim_appeal=0.05,
        machine_power=0.98,
        leader_strength=0.85,
        stability_reputation=0.90,
        change_reputation=0.10,
        security_reputation=0.95,
        economic_competence=0.55,
        regional_affinity={
            "Столична Община": 0.41,
            "Сапарева Баня": 0.99,
            "Михайловград": 0.10,
            "Банкя": 0.05,
            "Банско": 0.45,
            "Варна": 0.42,
            "Търново": 0.60,
            "Перник": 0.45,
        },
    ),
    "Демократично Пустиняково": PartyProfile(
        name="Демократично Пустиняково",
        economic_position=-0.10,
        cultural_position=-0.85,
        regime_status=0.00,
        urban_appeal=0.90,
        working_class_appeal=0.15,
        traditionalist_appeal=0.05,
        progressive_appeal=0.95,
        minority_muslim_appeal=0.25,
        machine_power=0.25,
        leader_strength=0.70,
        stability_reputation=0.35,
        change_reputation=0.90,
        security_reputation=0.25,
        economic_competence=0.60,
        regional_affinity={
            "Столична Община": 0.40,
            "Сапарева Баня": 0.05,
            "Михайловград": 0.15,
            "Банкя": 0.34,
            "Банско": 0.25,
            "Варна": 0.35,
            "Търново": 0.10,
            "Перник": 0.30,
        },
    ),
    "ГЕРП": PartyProfile(
        name="ГЕРП",
        economic_position=0.70,
        cultural_position=0.30,
        regime_status=0.40,
        urban_appeal=0.75,
        working_class_appeal=0.50,
        traditionalist_appeal=0.40,
        progressive_appeal=0.30,
        minority_muslim_appeal=0.20,
        machine_power=0.70,
        leader_strength=0.75,
        stability_reputation=0.75,
        change_reputation=0.25,
        security_reputation=0.60,
        economic_competence=0.80,
        regional_affinity={
            "Столична Община": 0.75,
            "Сапарева Баня": 0.10,
            "Михайловград": 0.45,
            "Банкя": 0.20,
            "Банско": 0.45,
            "Варна": 0.38,
            "Търново": 0.30,
            "Перник": 0.63,
        },
    ),
    "СХДС": PartyProfile(
        name="СХДС",
        economic_position=0.25,
        cultural_position=0.80,
        regime_status=0.30,
        urban_appeal=0.65,
        working_class_appeal=0.65,
        traditionalist_appeal=0.85,
        progressive_appeal=0.05,
        minority_muslim_appeal=0.00,
        machine_power=0.25,
        leader_strength=0.50,
        stability_reputation=0.30,
        change_reputation=0.15,
        security_reputation=0.70,
        economic_competence=0.65,
        regional_affinity={
            "Столична Община": 0.45,
            "Сапарева Баня": 0.10,
            "Михайловград": 0.98,
            "Банкя": 0.05,
            "Банско": 0.40,
            "Варна": 0.40,
            "Търново": 0.35,
            "Перник": 0.38,
        },
    ),
    "ДПС": PartyProfile(
        name="ДПС",
        economic_position=0.00,
        cultural_position=0.35,
        regime_status=0.00,
        urban_appeal=0.40,
        working_class_appeal=0.65,
        traditionalist_appeal=0.50,
        progressive_appeal=0.30,
        minority_muslim_appeal=0.95,
        machine_power=0.85,
        leader_strength=0.80,
        stability_reputation=0.60,
        change_reputation=0.55,
        security_reputation=0.35,
        economic_competence=0.65,
        regional_affinity={
            "Столична Община": 0.22,
            "Сапарева Баня": 0.01,
            "Михайловград": 0.12,
            "Банкя": 0.90,
            "Банско": 0.22,
            "Варна": 0.25,
            "Търново": 0.12,
            "Перник": 0.20,
        },
    ),
    "Израждане": PartyProfile(
            name="Израждане",
            economic_position=0.30,
            cultural_position=0.80,
            regime_status=0.00,
            urban_appeal=0.05,
            working_class_appeal=0.65,
            traditionalist_appeal=0.95,
            progressive_appeal=0.00,
            minority_muslim_appeal=0.00,
            machine_power=0.05,
            leader_strength=0.90,
            stability_reputation=0.10,
            change_reputation=0.40,
            security_reputation=0.50,
            economic_competence=0.35,
            regional_affinity={
                "Столична Община": 0.10,
                "Сапарева Баня": 0.15,
                "Михайловград": 0.25,
                "Банкя": 0.05,
                "Банско": 0.35,
                "Варна": 0.25,
                "Търново": 0.45,
                "Перник": 0.35,
        },
    ),
    "Пустиняшка Промяна": PartyProfile(
            name="Пустиняшка Промяна",
            economic_position=0.60,
            cultural_position=-0.80,
            regime_status=0.00,
            urban_appeal=0.65,
            working_class_appeal=0.20,
            traditionalist_appeal=0.00,
            progressive_appeal=0.70,
            minority_muslim_appeal=0.00,
            machine_power=0.10,
            leader_strength=0.10,
            stability_reputation=0.05,
            change_reputation=0.70,
            security_reputation=0.05,
            economic_competence=0.45,
            regional_affinity={
                "Столична Община": 0.40,
                "Сапарева Баня": 0.05,
                "Михайловград": 0.10,
                "Банкя": 0.10,
                "Банско": 0.38,
                "Варна": 0.25,
                "Търново": 0.10,
                "Перник": 0.40,
        },
    ),
}