from models.region import RegionProfile


REGION_PROFILES = {
    "Столична Община": RegionProfile(
        name="Столична Община",
        population=2_140_000,
        agents=2490,
        education_mean=0.85,
        income_mean=0.80,
        urbanity_mean=0.95,
        turnout_mean=0.68,
        volatility_mean=0.55,
        traditionalism_mean=0.30,
        progressive_mean=0.80,
        regime_trust_mean=0.35,
        opposition_mean=0.60,
        patronage_mean=0.20,
        local_identity_mean=0.30,
        muslim_share=0.06,
    ),
    "Сапарева Баня": RegionProfile(
        name="Сапарева Баня",
        population=1_250_000,
        agents=1450,
        education_mean=0.45,
        income_mean=0.50,
        urbanity_mean=0.60,
        turnout_mean=0.72,
        volatility_mean=0.15,
        traditionalism_mean=0.70,
        progressive_mean=0.15,
        regime_trust_mean=0.90,
        opposition_mean=0.10,
        patronage_mean=0.95,
        local_identity_mean=0.65,
        muslim_share=0.03,
    ),
    "Михайловград": RegionProfile(
        name="Михайловград",
        population=1_700_000,
        agents=1980,
        education_mean=0.72,
        income_mean=0.70,
        urbanity_mean=0.90,
        turnout_mean=0.64,
        volatility_mean=0.45,
        traditionalism_mean=0.40,
        progressive_mean=0.60,
        regime_trust_mean=0.35,
        opposition_mean=0.55,
        patronage_mean=0.30,
        local_identity_mean=0.40,
        muslim_share=0.08,
    ),
    "Банкя": RegionProfile(
        name="Банкя",
        population=670_000,
        agents=790,
        education_mean=0.52,
        income_mean=0.50,
        urbanity_mean=0.55,
        turnout_mean=0.66,
        volatility_mean=0.40,
        traditionalism_mean=0.55,
        progressive_mean=0.35,
        regime_trust_mean=0.10,
        opposition_mean=0.80,
        patronage_mean=0.40,
        local_identity_mean=0.90,
        muslim_share=0.70,
    ),
    "Банско": RegionProfile(
        name="Банско",
        population=665_000,
        agents=770,
        education_mean=0.50,
        income_mean=0.48,
        urbanity_mean=0.40,
        turnout_mean=0.58,
        volatility_mean=0.65,
        traditionalism_mean=0.55,
        progressive_mean=0.35,
        regime_trust_mean=0.40,
        opposition_mean=0.40,
        patronage_mean=0.35,
        local_identity_mean=0.50,
        muslim_share=0.06,
    ),
    "Варна": RegionProfile(
        name="Варна",
        population=540_000,
        agents=630,
        education_mean=0.54,
        income_mean=0.52,
        urbanity_mean=0.55,
        turnout_mean=0.60,
        volatility_mean=0.70,
        traditionalism_mean=0.50,
        progressive_mean=0.45,
        regime_trust_mean=0.45,
        opposition_mean=0.45,
        patronage_mean=0.35,
        local_identity_mean=0.45,
        muslim_share=0.05,
    ),
    "Търново": RegionProfile(
        name="Търново",
        population=580_000,
        agents=670,
        education_mean=0.58,
        income_mean=0.50,
        urbanity_mean=0.45,
        turnout_mean=0.61,
        volatility_mean=0.42,
        traditionalism_mean=0.75,
        progressive_mean=0.20,
        regime_trust_mean=0.50,
        opposition_mean=0.45,
        patronage_mean=0.30,
        local_identity_mean=0.85,
        muslim_share=0.03,
    ),
    "Перник": RegionProfile(
        name="Перник",
        population=1_050_000,
        agents=1220,
        education_mean=0.56,
        income_mean=0.53,
        urbanity_mean=0.50,
        turnout_mean=0.60,
        volatility_mean=0.55,
        traditionalism_mean=0.52,
        progressive_mean=0.42,
        regime_trust_mean=0.48,
        opposition_mean=0.42,
        patronage_mean=0.38,
        local_identity_mean=0.40,
        muslim_share=0.04,
    ),
}